### ISSUE TITLE
Multi-Row Copy/Paste from Excel and React-DataSheet

### ISSUE THREAD

**Issue by tleish** [nadbm/react-datasheet#10]
**Copy/Paste from Paste to React-DataSheet to Excel**
This seems to work well

**Copy/Paste from Paste to Excel to React-DataSheet**
This works when if I am only copying data from one row, but more than one row does not paste properly into React-DataSheet is not working.  It mashes all the data into a single row.

OS: macOS 10.12.3
Browser: Version 56.0.2924.87 (64-bit)
Excel: 15.31

**Comment by nadbm** [comment]
Thanks for reporting, should work fine now. Wasn't checking for carriage return, only newline
