### ISSUE TITLE
Programatically select a cell?

### ISSUE THREAD

**Issue by darajava** [nadbm/react-datasheet#102]
Is it possible to automate selecting a cell?

Something as simple `grid[row][col] = {value, selected: true};` in `onCellsChanged`, or some other way.

I can't seem to find a way to do this.

**Comment by nadbm** [comment]
https://github.com/nadbm/react-datasheet#advanced-options 
I think you're looking for the selected option.

**Comment by darajava** [comment]
Thanks for the fast reply, you solved my problem! Although I did notice that when the selected option is present, but undefined it doesn't allow manual selection. I think this shouldn't be the case, and it should check for the value of the prop, not the existence of it. Leads to some messy code for me.

Thanks again!

**Comment by darajava** [comment]
Also, even when the selection is present and in correct form, the user is not allowed to manually override the select. Is there a workaround for this?

**Comment by nadbm** [comment]
Hey @darajava , that prop was added to make selection fully controlled, you can achieve the user select as long as you combine with the "onSelect" prop. 
 https://github.com/nadbm/react-datasheet/issues/60

**Comment by darajava** [comment]
Thank you :)
