### ISSUE TITLE
Copy and Paste overflow rows got lost

### ISSUE THREAD

**Issue by soulclown** [nadbm/react-datasheet#110]
I find the library well done and very useful.
I have troubles using the feature of copy and paste when the original clipboard contains more lines then data has in the begin.
I try to describe the problem i cannot solve with a practical example:
1. i have 5 elements in `data` prop: the library renders **5** excel rows;
2. I use the method `parsePaste` to manipulate the clipboard and returns **10** rows.
3. Copy and paste has been done on row **4** (information not available in `parsePaste` function).
4. The method `onCellsChanged` has `changes` array with length **2** (the row 4 and the row 5).

Now comes my question: 
How do i handle the remaining **8** rows that got lost between `parsePaste` and `onCellsChanged` in a elegant way?
Thank you so much.

**Comment by nadbm** [comment]
@soulclown The second argument is what you need: 
https://github.com/nadbm/react-datasheet#oncellschangedarrayofchanges-arrayofadditions-handler

**Comment by soulclown** [comment]
Thanks @nadbm  !
