### ISSUE TITLE
Extra cell modified on paste

### ISSUE THREAD

**Issue by shawnmitchell** [nadbm/react-datasheet#111]
Copy this:

<img width="417" alt="copy" src="https://user-images.githubusercontent.com/3594613/43017167-2b8bb90a-8c23-11e8-875a-4f58cccae86f.png">

Paste and get this: 

<img width="733" alt="paste" src="https://user-images.githubusercontent.com/3594613/43017192-39dbb456-8c23-11e8-8d4f-a37376bfb4a6.png">

Not sure what is causing that blank cell update to be added. Any help would be greatly appreciated.

**Comment by nadbm** [comment]
@shawnmitchell where are you copying from? Currently the parser looks for "\n" for a new row and "\t" to assume a new column. You can use your own custom parser via : parsePaste 
https://github.com/nadbm/react-datasheet#options

**Comment by shawnmitchell** [comment]
Thanks for the instant reply! Copying from Excel in a Windows VM. Will check out what's received in parsePaste.

**Comment by shawnmitchell** [comment]
It does appear that this is related to copying from Excel running in Parallels. Numbers, Excel Online, etc. all work as expected.

**Comment by shawnmitchell** [comment]
This seems to have fixed my issue

```const parsePaste = clipboardData => {
   return clipboardData
      .split(/\r\n|\n|\r/)
      .filter(row => row.length > 0)
      .map(row => row.split("\t"));
  };
```

**Comment by robotanz** [comment]
I have a similar issue when copying from Excel (Windows 10). When taking a range of 3 values of the same column, the paste action actually modifies 4 values: the 3 first are correct and the fourth is an empty cell, overwriting previous value...

**Comment by gsmari** [comment]
In my case I only want to exclude the last element, if it is empty

```javascript
    const pastedSplit = pasted.split(/\r\n|\n|\r/)
      .map(row => row.split("\t"));
    if(pastedSplit[pastedSplit.length-1][0].length < 1)
      pastedSplit.pop(); // if last element is an empty string, remove it
```
