### ISSUE TITLE
Pasting multiple cells doesn't act as expected if selection is created from the bottom up

### ISSUE THREAD

**Issue by slope-taylor** [nadbm/react-datasheet#116]
Pasting appears to always paste from the "start" selection cell and go downwards, so if a user copies 3 cells, selects 3 cells to paste into from the bottom up, and then pastes, the cells paste from the bottom most cell of the selection and go downward.  This seems counter intuitive.

**Comment by nadbm** [comment]
The fix for this is fairly simple as the [current implementation](https://github.com/nadbm/react-datasheet/blob/master/src/DataSheet.js#L142
) just pastes forward. 
Before implementing however, consider google sheets: I do believe the implementation reflects that.

**Comment by slope-taylor** [comment]
@nadbm Google sheets functions the way I would expect, where the top/left-most cell of the selection is the starting point for the paste.  Google does, however, leave the original starting cell selected for keyboard nav, but that implementation would be more complicated than needed initially, I would think.

**Comment by nadbm** [comment]
@slope-taylor Ah I see what you mean. That makes sense, the simple fix is to compare the start/end selected values and choose the smallest indexed cell to start pasting. 
The keyboard nav could probably also be achieved, but that's a seperate issue

**Comment by slope-taylor** [comment]
@nadbm Yep, I agree.  The fix is simple like you said... if I could get a working repository going I'd put in a PR myself, but I'd been having some trouble.  I'll see if I can't get something going.

**Comment by witalewski** [comment]
Hi,

I was looking for open source projects on GitHub I could make small contributions to, just for practice.

I created a PR which solves this issue: https://github.com/nadbm/react-datasheet/pull/120

Apart from pasting to cells selected from bottom up, it also covers the cases of cells selected from right to left or in multiple rows and columns (top right to bottom left, top left to bottom right etc.)

Please consider merging the PR, this would be my first contribution here :)

**Comment by slope-taylor** [comment]
This seems to work now that this PR is merged.  Thanks @witalewski !
