### ISSUE TITLE
Apply formats to cell editor

### ISSUE THREAD

**Issue by saityro** [nadbm/react-datasheet#117]
Hello there!
first of all, I tried several tables and i'm loving this one in particular, awesome work!

I'm trying to apply especific formats to different cells' input.  I will probably learn to use your existing component: (...) prop to create different types of inputs there but i realized that it may be nice to have a `"format": ""` tag that can control the input type in the grid elements.

For example if in the grid data I add the cell:
`{ value: null, format:"number"}`, this format could change the type: "" prop on the input. So now this particullar cell will only accept numbers.

Just one idea. I'm not enougth experienced to to change your code but i will post my solution with components if i get it working in case it helps somebody with same issue :)

**Comment by nadbm** [comment]
hey @saityro , thank you for the praise.
The validation was purposely left out.   

```jsx
<ReactDataSheet
        data={this.state.grid}
        valueRenderer={(cell) => cell.value}
        onCellsChanged={changes => {
          const grid = this.state.grid.map(row => [...row])
          changes.forEach(({cell, row, col, value}) => {
```
Insert a validator here, you have access to your cell ie cell.format if you like. 
```jsx
const validated = cell.format === 'number' ? parseFloat(value) : value
```

```jsx
            grid[row][col] = {...grid[row][col], value: validated}
          })
          this.setState({grid})
        }}
      />
```

**Comment by saityro** [comment]
Awesome! It works like a charm :). And playing with it I understood more stuff about the code :)

Being one of the features that people coming from excel is used to, you don't think is a good idea to add it in a more native way? Maybe in one of the examples or in the doc? I'm kins of new to react but just tell me if I can help 

Thank you again for the answer!

**Comment by npips1991** [comment]
hi hello
i am try to use check runtime validation  like (Mobile , email ..) and many more but how??

**Comment by addTvb** [comment]
Hello @nadbm, can you add an example with validations to documentation, for more clarity?
