### ISSUE TITLE
Passing in an onSelect function seems to break the built-in selection/keyboard nav

### ISSUE THREAD

**Issue by slope-taylor** [nadbm/react-datasheet#118]
Passing in an onSelect function, even one that doesn't do anything, changes the behavior of the grid such that keyboard nav no longer works unless you double click a cell first and then exit the editing.  Similar problems with multi-select, etc when an onSelect function is passed.  I would've expected this to just be a callback, is that not the case?

**Comment by nadbm** [comment]
hey @slope-taylor onSelect must be used in conjunction with selected
```
state = {selected: {start: null, end: null}}
<Datasheet
   selected = this.state.selected
   onSelect = (selected) => this.setState({selected: selected})
/>
```

**Comment by slope-taylor** [comment]
Hi @nadbm ! Thanks for the quick response!

I tried your suggestion, but this appears to break the functionality in a different way.  The onSelect seems to execute in a continuous loop once I click on something, as if the mouseUp event never fires.  Dragging the mouse around after clicking on a cell continues to select other cells even though I've let up on the mouse button.  It's worth noting that I'm also using the following props: sheetRenderer, valueRenderer, valueViewer, onCellsChanged, rowRenderer, onSelect, parsePaste, and selected.

**Comment by nadbm** [comment]
hey @slope-taylor , can you make a fiddle ?

**Comment by slope-taylor** [comment]
@nadbm While trying to make a fiddle, I came across the root cause.  It appears that using a non-arrow function for sheetRenderer with a "this" binding is what was causing the behavior.

For example:
`<Datasheet
   selected = this.state.selected
   onSelect = (selected) => this.setState({selected: selected})
   sheetRenderer = {this.sheetRenderer.bind(this)} // This is a problem.
/>`

I was able to avoid this by converting my sheet renderer into an arrow function to maintain the lexical scope of the "this" keyword without the binding.  I'm not sure if this is actually an issue or if I was just doing it wrong?

**Comment by nadbm** [comment]
@slope-taylor I would need to see the full code to be certain binding within render can definitely cause issues. 
The sheet renderer function you are passing is being created every time the render function is being called. bind(this) creates a new function every time.
Im guessing every time you are calling this.setState() , your top level component is being re-rendered, and thus sheetRenderer is being created again.

**Comment by slope-taylor** [comment]
@nadbm That makes sense, thanks for your help.  It's probably not worth trying to recreate since the way I was binding is really a performance problem in react anyways, and users of this library hopefully aren't binding like that.

**Comment by konrad-garus** [comment]
To the next poor soul who spends hours banging their head against the wall, here's a piece of advice.

I was running into the infinite loop nightmare with a trivial arrow function for `sheetRenderer`:

```
sheetRenderer={sheetProps => {
   return (
     <table className={sheetProps.className}>
       <tbody>{sheetProps.children}</tbody>
     </table>
   );
}}
```

Using a stable and bound function reference did the trick:

```
class Ds extends React.Component {
  constructor(props) {
    super(props);
    this.state = { grid: [/* ... */]; selected: null };
    this.sheetRenderer = this.sheetRenderer.bind(this);
  }
  sheetRenderer(sheetProps) {
    return (
      <table className={sheetProps.className}>
        <tbody>{sheetProps.children}</tbody>
      </table>
    );
  }
  render() {
    return (
      <div>
        <ReactDataSheet
          data={this.state.grid}
          valueRenderer={cell => cell.value}
          sheetRenderer={this.sheetRenderer}
          selected={this.state.selected}
          onSelect={selected => this.setState({ selected })}
        />
      </div>
    );
}
```

However, using that same function in an arrow function leads to the loop issue again:

```
        <ReactDataSheet
          data={this.state.grid}
          valueRenderer={cell => cell.value}
          sheetRenderer={sheetProps => this.sheetRenderer(sheetProps)}
          selected={this.state.selected}
          onSelect={selected => this.setState({ selected })}
        />
```

I would actually call it a bug, Maybe I'm not understanding something, though. Anyway, here's some stuff to check if you run into this.

**Comment by lveillard** [comment]
Maybe is there a way to do it without creating classes? 
Classess are soooo 2019 😅

**Comment by lveillard** [comment]
Ok, it just works fine, if somebody is looking for this:

```
  const [selected, setSelected] = useState({
    start: { i: 0, j: 0 },
    end: { i: 0, j: 0 },
  });
```

and this params in the dataSheet:

`            selected={selected}
            onSelect={(selected) => setSelected(selected)}
`

Will just work fine

**Comment by archywillhe** [comment]
nope; ceases to work poerply once you have a custom cellRenderer zzz
