### ISSUE TITLE
When you use the custom component cell, you are not able to modify their props

### ISSUE THREAD

**Issue by Trireir** [nadbm/react-datasheet#119]
If you use a custom component for a cell, and have the info saved in a reducer f.e., you are not able to modify the props of the component.

In my case I'm creating the datasheet dynamically with some info stored in a reducer. The problem came when I modify that info, because i'm not able to modify the props sent to the component.

In my opinion, this could be solved easily adding a new value to the cell object called componentProps, and then react-datasheet can create the element with the props needed. I can prepare a PR in case  you think this is something useful.

**Comment by patrick-jones** [comment]
You can already do this by using a custom renderer. See, for example, [the `dataEditor` in the readme](https://github.com/nadbm/react-datasheet#custom-renderers) or the ["Sheet with Customer Renderers" example](https://github.com/nadbm/react-datasheet/blob/79e31e120afc03810847b56c0fd497dc94e82d7e/docs/src/examples/CustomRendererSheet.js).

To handle your specific case:

```jsx
class MyComponent extends Component {

  dataEditor = dataEditorProps => {
    if (dataEditorProps.col === 0) {
      return (
        <MyCustomEditorControl 
          {...dataEditorProps} 
          {...dataEditorProps.cell.componentProps} 
        />
      );
    }
    return (<DataEditor {...dataEditorProps}/>)
  };

  render() {
    return (
      <ReactDatasheet
        data={this.props.data}
        valueRenderer={(cell) => cell.value}
        dataEditor={this.dataEditor}
        onCellsChanged={this.props.onCellsChanged}
      />
    );
  }
}
```
If you want to show the component during view mode also, you can implement `valueViewer` in the same way.

> In my opinion, this could be solved easily adding a new value to the cell object called componentProps, and then react-datasheet can create the element with the props needed. 

Given that this case is easily handled with custom renderers, I don't think it is a good idea to burden the core library with yet another property. It makes the component's interface unnecessarily noisy.

**Comment by Trireir** [comment]
Okey, sounds good for me. I'll try to update my project to fit in this idea. Thank you :)
