### ISSUE TITLE
Change background color to a cell?

### ISSUE THREAD

**Issue by idowolf** [nadbm/react-datasheet#131]
I set a "className" to a cell and set custom attributes in my CSS file. When I set "color" property, the text's color changes, but not the cell's background color. "background-color" and "fill" don't do anything as far as I can see. I couldn't find information about it in the examples. How can I set the cell's background color?

**Comment by mitchellwarr** [comment]
If you mean the selected cells, currently they use an inset box-shadow for their coloring
