### ISSUE TITLE
Enter as newline in cell being edited

### ISSUE THREAD

**Issue by zgazak** [nadbm/react-datasheet#137]
Loving this repo!  What is the best way to add a custom key press handler so that cells can register a new line instead of ENTER_KEY committing the change and exiting the editor?

**Comment by nadbm** [comment]
You need to have a custom data editor per cell:
https://github.com/nadbm/react-datasheet#custom-renderers
https://github.com/nadbm/react-datasheet#data-editor

Here's an example being used:
https://github.com/nadbm/react-datasheet/blob/master/docs/src/examples/CustomRendererSheet.js#L57

**Comment by zgazak** [comment]
Thank you so much, I was looking in the wrong place.
