### ISSUE TITLE
Provide the location of the pasted information on `parsePaste`

### ISSUE THREAD

**Issue by nihey** [nadbm/react-datasheet#140]
I'm building a feature for my application in which I would like the grid to auto grow when I paste more data than the number of cells the table has.

For this, I would need access to the location of the pasted data, e.g.:

- My grid has `100 rows`
- The user pastes something that has `80 rows` on row `#40`
- I have to resize my grid should now resize to `120 rows`.

**Comment by nadbm** [comment]
@nihey The problem you’re describing is handled via “onCellsChanged”, its second parameter “additions” passes the overflowing pasted members

**Comment by nihey** [comment]
@nadbm Oops, completely missed that one! But thanks for pointing me on the right direction, I'll handle it this way, it should be cleaner.
