### ISSUE TITLE
Sheet selections on sheet with rowspan and colspan incorrect

### ISSUE THREAD

**Issue by derblitz** [nadbm/react-datasheet#142]
When using colspan and/or rowspan in a sheet, the selections are incorrect (see attached gif please).

It seems that the method used to check whether a cell is selected or not, does not consider the possibility of colspan and rowspan - react datasheet selects cells like they were not "merged".

![colspan rowspan selections](https://user-images.githubusercontent.com/20650077/51351452-31dfef80-1aab-11e9-8b30-3744fce3759b.gif)

**Comment by nadbm** [comment]
Unfortunately the codebase does not consider colspan/rowspan. The selection of cells is done via a coordinate system (cell (a,b) => cell (c,d)).

**Comment by gowarriori** [comment]
Will this be fixed in the future? By the way @derblitz  How did you add the colSpan, I followed the example it does not work for me
