### ISSUE TITLE
ComponentSheet.js Example is not working with latest version of react-select

### ISSUE THREAD

**Issue by mk48** [nadbm/react-datasheet#143]
Below example is not working with latest version of react-select

https://nadbm.github.io/react-datasheet/
![image](https://user-images.githubusercontent.com/3082469/53579813-45996e00-3ba0-11e9-92e0-b1362f1c21b6.png)

the above example is using "react-select ^1.0.0-rc.3" version which is very old, current version is 2.4.1

I copied the ComponentSheet (react-datasheet/docs/src/examples/ComponentSheet.js) example and created a CodeSandbox, typing grocery item is not selecting values.

Please open the below sandbox and try the same.
https://codesandbox.io/s/jpnrrm7xp5

**Comment by nadbm** [comment]
Hey @mk48 , the react-select API changed slightly. 
          autofocus -> autoFocus
          openOnFocus ->  defaultMenuIsOpen

The following is a working version:
https://codesandbox.io/embed/2oyo8745xp

**Comment by mk48** [comment]
Thanks @nadbm

**Comment by Sagar-Tomar** [comment]
Thanks nadbm , Saved a lot of time.
