### ISSUE TITLE
Event in Typescript definition for onCommit should be optional

### ISSUE THREAD

**Issue by shawnmitchell** [nadbm/react-datasheet#153]
Intellisense hint states "if you pass a KeyboardEvent as the second argument..." 
And the source code checks for a non-null value of `e`

But the type definition has the event as required.

If a custom component wants some other trigger to commit a cell value, it should be possible to omit the event. 

```
/** function (newValue, [event]) {} A callback to indicate that editing is over, here is the final value. If you pass a KeyboardEvent as the second argument, React-DataSheet will perform default navigation for you (for example, going down to the next row if you hit the enter key). You actually don't need to use onCommit if the default keyboard handling is good enough for you. */
        onCommit: (newValue: V, event: React.KeyboardEvent<HTMLElement>) => void;
       

```
```
handleCommit (value, e) {
    const {onChange, onNavigate} = this.props
    if (value !== initialData(this.props)) {
      this.setState({ value, committing: true })
      onChange(this.props.row, this.props.col, value)
    } else {
      this.handleRevert()
    }
    if (e) {
      e.preventDefault()
      onNavigate(e, true)
    }
  }

```

**Comment by shawnmitchell** [comment]
I have not contributed to OSS before but I'd be happy to create a pull request for this if the owner agrees it's an issue. I can probably also tackle #139 while I'm in there as it seems like a one-liner.

**Comment by nadbm** [comment]
Thank you, the type file hasnt gotten much attention. Will merge soon
