### ISSUE TITLE
How to set fixed width of a cell?

### ISSUE THREAD

**Issue by annjawn** [nadbm/react-datasheet#158]
This is a very useful library, thanks to all the contributors for their work. I was hoping this would be simple enough to set the width of the cell but I can't seem to figure out how to use it.

How do I set the width of my cells to fixed? and also how do I make sure that the width remains the same after typing in a long text in it.

What could achieve so far is:

Before
<img width="483" alt="Screen Shot 2019-06-06 at 11 32 23 PM" src="https://user-images.githubusercontent.com/26977294/59085440-70881200-88b3-11e9-88bf-8163876869b4.png">

After
<img width="597" alt="Screen Shot 2019-06-06 at 11 32 38 PM" src="https://user-images.githubusercontent.com/26977294/59085445-74b42f80-88b3-11e9-8798-b1c4392e9dfb.png">

as you can see, my cell is kind of expanding instead of the text clipping. I've tried `overflow="clip"` in `<Datasheet .../>` but I am not sure if it works. I have also tried this as a row -

```json
     [
        { "readOnly": true, "value": "Freight", "width": 100 },
        { "value": "", "key":"1", "width": 100, "overflow": "clip" },
        { "value": "", "key":"2","width": 100, "overflow": "clip" },
        { "value": "", "key":"3","width": 100, "overflow": "clip" },
        { "value": "", "key":"4","width": 100, "overflow": "clip" },
        { "value": "", "key":"5","width": 100, "overflow": "clip" },
        { "value": "", "key":"6","width": 100, "overflow": "clip" },
        { "value": "", "key":"7","width": 100, "overflow": "clip" },
        { "value": "", "key":"8","width": 100, "overflow": "clip" }
      ]
```
but this doesn't work either. And my datasheet component looks like this

```html
      <Datasheet
              data={this.state.grid}
              sheetRenderer={props => (
                        <table className={props.className}>
                          <thead>
                            <tr>
                              <th />
                              {grid1.columns.map(col => (
                                <th key={col.label} style={{textAlign:"center"}}>
                                  <Text strong>{col.label}</Text>
                                </th>
                              ))}
                            </tr>
                          </thead>
                          <tbody>{props.children}</tbody>
                        </table>
                      )}
             overflow="clip"
             valueRenderer={cell => cell.value}
             onCellsChanged={changes => {
                        const grid = this.state.grid.map(row => [...row]);
                        changes.forEach(({ cell, row, col, value }) => {
                          grid[row][col] = { ...grid[row][col], value };
                        });
                        this.setState({ grid });
              }}
     />
```

I have looked at #29 but I have no idea how to use this. I've been through the documentation and all the examples and tried various things but no luck so far. A little help with the usage would be appreciated.

**Comment by nadbm** [comment]
hey @annjawn, tried to reproduce your issue. Your second one (overflow='clip') should have worked. Can you try the following, add the fiollowing css:

```css
table.datagrid {
  width: 100%;
}
```

**Comment by annjawn** [comment]
Hey Sorry for the late response. I had to do this with the CSS to make it work. The Width `inherit` is what did the trick. I also had to do the `box-sizing: content-box` otherwise the editor `<input/>` was showing up with a weird shorter height.

 ```bash
 .data-grid-container .data-grid .cell .value-viewer {
    display: block;
    box-sizing: content-box;
    width: inherit;
  }
 
  .data-grid-container .data-grid .cell .data-editor{
    display: block;
    box-sizing: content-box;
    height: inherit;
  }
```
