### ISSUE TITLE
React Warning: componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by polys** [nadbm/react-datasheet#164]
After upgrading React to v16.9.0, I started getting this warning in the console:

> **Warning: `componentWillReceiveProps` has been renamed, and is not recommended for use.** 
> See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to `componentDidUpdate`.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static `getDerivedStateFromProps`. Learn more at: https://fb.me/react-derived-state
> * Rename `componentWillReceiveProps` to `UNSAFE_componentWillReceiveProps` to suppress this warning in non-strict mode. In React 17.x, only the `UNSAFE_` name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: `DataCell`

It would be nice if this was addressed before React 17.x I guess. 
Many thanks!

**Comment by Flaneder** [comment]
Wouldn't it be enough to follow the third advice for now:

> Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps [...]

I would still keep this ticket open though.

**Comment by nadbm** [comment]
This is fixed with this merged PR: https://github.com/nadbm/react-datasheet/pull/178

**Comment by polys** [comment]
Many thanks @nadbm!
