### ISSUE TITLE
Handling context menu when multiple cells are selected

### ISSUE THREAD

**Issue by nadzimo** [nadbm/react-datasheet#184]
Great library, thanks a lot for this!

When I have multiple cells selected and right-click to trigger `onContextMenu` of `ReactDataSheet`, the selection is going away and instead the cell I happen to right-click on gets selected.  
What is the best way to trigger onContextMenu while keeping the selected cells selected?

**Comment by nadbm** [comment]
Currently no. The current onContextMenu also passes back the cell it is referring to. However, changing the code to fit that need shouldn't be too difficult. 

To update the code would be to do the following:
* Check the button clicked on "onMouseDown" and making sure it is not the context button. 
* Pass all the selected cells on contextMenu function

**Comment by nadzimo** [comment]
thank you – that's what I ended up doing.

**Comment by imgss** [comment]
I got the same problem, that's helped
