### ISSUE TITLE
Super expression must either be null or a function, not undefined - troubleshooting with import of react-datasheet

### ISSUE THREAD

**Issue by fzoozai** [nadbm/react-datasheet#19]
Hi,

I just tried to integrate the react-datasheet component into my project where I faced some issues with regard to rendering the component. What could be the reason for that? I saw the last commit in the react-datasheet project was about 23 hours ago. I also followed the given example step by step from the basic usage section. I appreciate any help.

fzoozai

**Comment by nadbm** [comment]
hey @fzoozai, I'll need more details as to your issue. Is this an issue introduced in the new version? Can you try out an older tag ? thanks

**Comment by fzoozai** [comment]
@nadbm
my current react version is "react": "^0.14.3"

While trying to figure out how to solve my problem I checked whether I get the error by only including the data-sheet lib into my project like: 

<img width="553" alt="datasheet-issue" src="https://cloud.githubusercontent.com/assets/10197484/26561445/d9d45038-44be-11e7-9a59-f583103b6ce6.png">

As expected I got:
<img width="653" alt="screen shot 2017-05-29 at 22 36 28" src="https://cloud.githubusercontent.com/assets/10197484/26561501/4c1a611e-44bf-11e7-93aa-d38f9eb38ccb.png">

Then I removed `import ReactDataSheet from 'react-datasheet';` and got rid of the error message and the Hello World Message shown.
That's why I thought the reason for that could have something to do with the last commit within the data-sheet project.

**Comment by nadbm** [comment]
@fzoozai Any chance your project is up on github? I'd like to reproduce this locally
