### ISSUE TITLE
Navigate keys make document scroll at version 1.4.1

### ISSUE THREAD

**Issue by cr4zyc4t** [nadbm/react-datasheet#208]
Use navigate keys (up/down keys) to navigate selected cell inside sheet:
v1.4.0 - work as expected: selected cell navigate correctly inside sheet, document body stay still, when selected cell reach boundary of sheet, document scroll is triggered.
v1.4.1 - not as expected: even selected cell does not reach sheet boundary, document body still scroll!

Example: Just run example in docs directory!

**Comment by nadbm** [comment]
Yikes, thanks for finding this, fixed it in 1.4.3
