### ISSUE TITLE
unmounting table is slow

### ISSUE THREAD

**Issue by lukas1994** [nadbm/react-datasheet#221]
Each DataCell needs to clear a timer which makes the unmount very slow:
![image](https://user-images.githubusercontent.com/6901762/84089667-785b2480-a9e7-11ea-9668-56a47a73d156.png)

![image](https://user-images.githubusercontent.com/6901762/84089690-8b6df480-a9e7-11ea-9076-327f4eca19f3.png)

Why do DataCells even need this timer? Is there a way to disable it?

**Comment by lukas1994** [comment]
Judging from the react-datasheet source code, you use timers to provide the updated prop into a custom CellRenderer: https://github.com/nadbm/react-datasheet#cell-renderer. (Basically, whenever a cell changed, that prop becomes true for 700 ms, and then resets back to false.) That’s why you need to clear timers when a cell unmounts.

Would be great if there was a way to disable [this](https://github.com/nadbm/react-datasheet/blob/c8678ab77f244ffdf529b76563b0247a88d89161/src/DataCell.js#L58).

cc @nadbm

**Comment by lukas1994** [comment]
Nice, thanks! Do you mind publishing a new version?

**Comment by nadbm** [comment]
Yes, give me a day to fix some tests, should have it by EOD

**Comment by nadbm** [comment]
> Yes, give me a day to fix some tests, should have it by EOD

published

**Comment by lukas1994** [comment]
How do I pass that prop to the DataCell though: https://github.com/nadbm/react-datasheet/blob/95c17d3348f1cb6afc9f47bbfad618cfc0327168/src/DataSheet.js#L678
