### ISSUE TITLE
Incorrect dependency as a library

### ISSUE THREAD

**Issue by moonrailgun** [nadbm/react-datasheet#227]
Hi, it looks like have a incorrect dependency in your config.

As a library, its have some dependency declare which is not good. The version of `husky`, `prettier` and others should place into `devDependencies`. 

In some project, its will cause error.

https://github.com/nadbm/react-datasheet/blob/c0db261fa625bb0b0a05d5ccdf0eb8356a085b78/package.json#L67-L72

**Comment by nadbm** [comment]
thanks for noticing! republished without the deps
