### ISSUE TITLE
"selected" and "read-only" class doesn't added after "cell" class. (typescript)

### ISSUE THREAD

**Issue by sugitlab** [nadbm/react-datasheet#232]
I'm using React.js with typescript.
Add similar table with your BasicSheet sample on my simple SPA application. Almost working, but "selected" and "readonly" styles are not applied, so I can't see which sell is selected now...

I debugged code with chrome extension (React developer tool).
In case "Component" tab, Sheet > Row > DataCell > cellRenderer has "cell read-only" or "cell selected" correctly. But in case "Elements" tab, span (data-grid-container) > table (data-grid) > tbody > tr > td has just "cell" in its class filed.

**Comment by iashris** [comment]
I got this issue as well.
