### ISSUE TITLE
Readonly mode?

### ISSUE THREAD

**Issue by aadrian** [nadbm/react-datasheet#24]
Hi,

is there a read-only mode for the grid?

So no change operations, but selection, copy, navigation etc. ?

Thank you.

**Comment by nadbm** [comment]
hey @aadrian, look at the basic sheet example, there are cells that are read-only. You just have to make all your cells read-only then you will get what you want.

**Comment by aadrian** [comment]
@nadbm but those are headers :) .

**Comment by nadbm** [comment]
yep, but look at the code, headers are not differentiated in this case. The only reason they are colored is because of the css file.

**Comment by aadrian** [comment]
@nadbm OK, I see. The headers don't seem to be able to sort or expand or autofilter out-of-the-box :( .

**Comment by nadbm** [comment]
Nope this is mainly a UI library, all that logic can be implemented on a top level component to this.

**Comment by aadrian** [comment]
@nadbm would be nice if the component would be able to do that :) .
