### ISSUE TITLE
Parameterize rendering

### ISSUE THREAD

**Issue by patrick-jones** [nadbm/react-datasheet#26]
I have been looking into adding row drag and drop using [react-dnd](https://react-dnd.github.io/react-dnd/). I'm hampered by the fact that the rendering function for the datasheet is a bit of a black box. For example, react-dnd would really like to wrap each `tr` in order to hook up event handling and drag representation, etc. 

Outside of react-dnd, it would be nice to be able to heavily customize rendering (such as putting custom controls at the beginning of the row, or a custom header component) without having to change the data model.

I'd like to extract out the current rendering functions and allow you to specify overrides via properties. The default would be to just keep doing what it's doing. I can do a PR for this.

**Comment by nadbm** [comment]
That seems reasonable, I did not see a use case for overriding TR initially, but drag and drop makes sense. If you can can keep the default behaviour, feel free to make the PR. I'd also like to see the drag and drop implementation, maybe you can link it in your repo and/or add it to the examples page

**Comment by patrick-jones** [comment]
Yes, I was thinking of at least making an example, and maybe setting up a separate package that could be treated as an add-on.
