### ISSUE TITLE
Text-Overflow

### ISSUE THREAD

**Issue by HaolinWang8** [nadbm/react-datasheet#27]
If the text is too long in two adjacent cell, the text will overlay each other and hard to distinct.
Is there a way to support text-overflow?
I have tried text-overflow to <span> but it seems not working.

**Comment by nadbm** [comment]
@HaolinWang8 Duplicate of #25 #7
For just hiding text overflowing you can add the following to your css : 
table.data-grid tr td.cell {
    overflow: hidden;
}

**Comment by HaolinWang8** [comment]
is it a way similar to
text-overflow: ellipsis;
