### ISSUE TITLE
Automatic OnChange problems

### ISSUE THREAD

**Issue by aiman-aew** [nadbm/react-datasheet#31]
Been trying to implement sending DB requests on change to the data grid but the function onChange is not being invoked.
Tried using this in the constructor 
this.onChange = this.onChange.bind(this); 

with the onChange={this.onChange} 
Managed to invoke the function, but its giving different errors per invoking if per cell change invoke or, by datasheet invoke.
as example if I delete a row using my delete keystroke it will give me 
Uncaught TypeError: Cannot read property 'key' of null which I guess because its not getting any cell correctly in function call.
Meanwhile invoking from the component using select gives another error.

**Comment by nadbm** [comment]
hey @aiman-aew, can you post some code on how you set up the component?

**Comment by aiman-aew** [comment]
hey @nadbm thank you for your reply here is the code where I am setting up the component.



`import React, {Component} from 'react';
import styled from 'styled-components';
import FloatingActionButton from 'material-ui/FloatingActionButton';
import Menu from 'material-ui/svg-icons/navigation/arrow-back';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider'; 
import {HashHistory} from 'react-router-dom';
import _ from 'lodash';
import Select from 'react-select';
import 'react-select/dist/react-select.css';
//plugin for UI on mobile devices
import injectTapEventPlugin from 'react-tap-event-plugin';

import config from '../../config';

import ReactDatasheet from 'react-datasheet';
import 'react-datasheet/lib/react-datasheet.css'; 

const Header = styled.header`
    text-align: center;
    font-size: 2em;
    font-family: 'Roboto', sans-serif;
    margin-top: 0px;
`;
 
const BackArrow = styled.div` 
    marginRight:'0px'; 
    marginTop:'0px';
`;

const goBack = function goBack(){
    HashHistory.goBack();
}

function ListItem(props) {
  // Correct! There is no need to specify the key here:
  return <li>{props.value}</li>;
}

class Criteria extends Component {

    constructor(props){
        super(props);
        this.onChange = this.onChange.bind(this);
        this.state = {
            data: [],
            items: 0
        };
        this.goBack = this.goBack.bind(this);
    }

    
    goBack (){
        this.props.history.push('/');
    }

    loadData(){
        fetch(`${config.serverUrl}/criteriaAPI`, {
                method: 'get',
                dataType: 'x-www-form-urlencoded',
                headers: {
                    'Accept': 'application/x-www-form-urlencoded; charset=UTF-8',
                    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                    'Access-Control-Allow-Origin':'*',
                    "Access-Control-Allow-Credentials" : true 
                },
            })
            .then(response => {
                 return response.json()
            })
            .then(responseData => {
                return responseData;
            })
            .then(data => {  
                this.setState({data : data});
                this.setState({items: data.length})
            })
            .catch(err => {
                console.log("fetch error" + err);
            });
    }

    componentDidMount(){
        this.loadData();
    }
    
    

    cellUpdate(state, changeCell, expr) {
        const scope = _.mapValues(state, (val) => isNaN(val.value) ? 0 : parseFloat(val.value))
       
        const updatedCell = _.assign({}, changeCell, this.computeExpr(changeCell.key, expr, scope))
        
        state[changeCell.key] = updatedCell

        _.each(state, (cell, key) => {
        if(cell.expr.charAt(0) === '=' && cell.expr.indexOf(changeCell.key) > -1 && key !== changeCell.key) {
            state = this.cellUpdate(state, cell, cell.expr)
        }
        })
        return state
    }

   
    onChange(changeCell, i, j, expr) {  
         console.log('logging');
        const state = _.assign({}, this.state);
        this.cellUpdate(state, changeCell, expr);
        this.setState(state); 
    }


    generateGrid () {
        const dataName = (id) => {
            if (this.state.data[id]) {
                const {securityCriteria} = this.state.data[id]
                return `${securityCriteria}`
            } else {
                return ''
            }
        }
        const dataDescription = (id) => {
            if (this.state.data[id]) {
                const {description} = this.state.data[id]
                return `${description}`
            } else {
                return ''
            }   
        }
        //component on change call
        const component = (id) => {
        return (
            <Select
            autofocus
            openOnFocus
            value={this.state && this.state.data[id]}
            //onChange={(opt) => this.setState({data: _.assign(this.state.data, {[id]: opt})})}
            onChange={this.onChange}
            options={this.options}
            />
        )
        }

        let rows = [
            [
                {readOnly: true, colSpan: 2, value: 'Criteria List'}
            ],
            [
                {
                    readOnly: true, value: 'Criteria'
                },
                
                { 
                    value: 'Items', 
                    component: (
                        <div style={{
                            textAlign: 'left',
                            padding: '5px 10px',
                            color: '#888'
                        }}> Description
                        <div style={{
                            float: 'right', 
                            background: '#CCC', 
                            borderRadius: '2px', 
                            padding: '2px 20px', 
                            backgroundColor: '#e63946', 
                            color: 'white', cursor: 'pointer', 
                            fontSize: '9px'
                            }} onClick={()=>{console.log("add");this.setState({items: this.state.items+1})}}> add item</div> 
                        </div>
                    ), 
                    forceComponent: true
                }
            ]
        ]
        rows = rows.concat(_.range(0, this.state.items ).map(
            id => [
                {readOnly: false, value: dataName(id), component: component(id)}, 
                {value: dataDescription(id), component: component(id)}
                ]))
        //rows = rows.concat([[{readOnly: true, value: 'Total'}, {readOnly: true, value: `${total.toFixed(2)} $`}]])
        console.log(rows)
        return rows
    }


    render() {
   
        //console.log(this.state.data);
        return (   
                 <MuiThemeProvider> 
                    <div> 
                        <BackArrow>
                        <FloatingActionButton 
                                onTouchTap={this.goBack}
                        >
                                <Menu/>
                        </FloatingActionButton>
                        </BackArrow>

                        <Header>                         
                        <h2>Criteria</h2>
                        </Header>
                        
                        <ReactDatasheet 
                            data={this.generateGrid()}
                            valueRenderer={(cell) => cell.value}
                            dataRenderer={(cell) => cell.expr}
                            onChange={this.onChange} 
                        />  
                    </div>
                 </MuiThemeProvider>     
        ) 
    }
}

export default Criteria`

**Comment by nadbm** [comment]
I think you have a misunderstanding of what onChange does. You have <Select /> components being generated. onChange is for value cells that can be edited.

**Comment by aiman-aew** [comment]
Hello Nadim,

Upon reading the package code, specifically DataCell.js I noticed that you are loading the 'keys' onChange and the others, I guess this is what you meant by the component has its own method.

The thing is I am not knowing whether if its already loaded how should I use it.

Can you provide a similar case or code snippet I can refer to

Many Thanks!

**Comment by nadbm** [comment]
@aiman-aew 
No I meant, some of the cell objects, you are using <Select /> elements. Look at your code on the function ```generateGrid```.

These objects do not have a "key" parameter. And on your function ```cellUpdate``` you are looking for that value. 

Here's a snippet of how to properly use components 
https://github.com/nadbm/react-datasheet/blob/master/docs/src/examples/ComponentSheet.js

**Comment by aiman-aew** [comment]
i grid to use this but got an error that 

row.map is not a function

I guess this is because it needs an array of arrays as the dataset ? or else it won't work?
