### ISSUE TITLE
Where can I see the code examples that are on the website?

### ISSUE THREAD

**Issue by hamodey** [nadbm/react-datasheet#326]
The examples present on the website https://nadbm.github.io/react-datasheet/, are very good examples and I would like to see the implementation. Is there a place I can see this? 

Is is not present on the README.

Thanks

**Comment by ziponia** [comment]
Perhaps, this is what you are looking for 

https://github.com/nadbm/react-datasheet/tree/master/docs/src/examples

**Comment by hamodey** [comment]
Thank you very much! Will take a closer look :)
