### ISSUE TITLE
Paste more rows than that is defined by the `grid`. 

### ISSUE THREAD

**Issue by hamodey** [nadbm/react-datasheet#328]
Hi, 

Lets say I have a Grid of 5 Rows and 3 columns, however in my excel I have 10 Rows and 3 columns. 

Using the `onCellChanged` and possibly the `pasteParser` I would like to generate 10 Rows in my grid. 

Currently the Datasheet looks like this:
![image](https://user-images.githubusercontent.com/26579110/176420738-b1beec32-990f-4873-a586-8e9e7b2b0423.png)

I would like to paste this data: 
![image](https://user-images.githubusercontent.com/26579110/176420786-9237c4cd-0cd9-4a51-9189-7100d265b191.png)

To end up looking like this: 

![image](https://user-images.githubusercontent.com/26579110/176420840-0a1dd584-c961-4ce4-a61c-21cf46e7da04.png)

From reading the source code I can see that there is: 

``` javascript
parsePaste={(pasted) => {
         //do something
        }}
```

However, this seems to overwrite the current paste functionality, is there a way I can extend that approach?

Thank you :)

**Comment by BaherZ** [comment]
onCellsChanged takes in 2 params, "changes" and "additions", you can use the additions to see the data that you copied that do not have a place to copy yet, you can then work with that info to add additional rows to your sheet

**Comment by hamodey** [comment]
Awesome, thanks for response I will have a look at that approach. 

I have had some time to apply functionality that does the above, but has small bugs for row length. 

I will take yours into account and see if that helps! :)
