### ISSUE TITLE
Possible Bug: When editing a cell and press left/right arrow key, editing stops and cell selection moves

### ISSUE THREAD

**Issue by kylegoetz** [nadbm/react-datasheet#37]
Maybe the expected behavior should be that the cursor within the editing field moves left/right. In any case, #36 would make this customizable.

**Comment by nadbm** [comment]
What browser are you on ? This should not happen

https://nadbm.github.io/react-datasheet/    <- If I'm editing and moving cursor here, it remains in edit mode.

**Comment by nadbm** [comment]
Also note that it matters how you enter edit mode. If it is double click or by pressing enter, the arrow keys dont get you out of edit. 

However if you start typing without doing anything, you get into immediate edit. In that case pressing arrow moves cells right away. This is a replication of Excel behaviour.

**Comment by kylegoetz** [comment]
Understood. I didn't realize that it behaved different depending on how you edit. I think I was always just typing without clicking. Couple with a teammate emailing me with this "bug" and I didn't bother to think about how Excel does it.
