### ISSUE TITLE
Enhancement: allow pre-parsing of pasted data

### ISSUE THREAD

**Issue by bttmly** [nadbm/react-datasheet#38]
The issue I have is I have users pasting data where the intended rows are separated by something besides newlines, and the cells are separated by something besides tabs. I'm wondering if you would be open to adding a `parsePaste` prop or similar, to customize how we initially parse data that a user pastes in. Basically I want to be able to customize the following code:

```js
      // (this starts at L103 in DataSheet.js)
      const pasteData = e.clipboardData
        .getData('text/plain')
        .split(/\r\n|\n|\r/)
        .map((row) => row.split('\t'));
```

I propose something along the lines of:

```js
function defaultParsePaste (str) {
  return str.split(/\r\n|\n|\r/).map((row) => row.split('\t'));
}


// later on...

const parser = this.props.parsePaste || defaultParsePaste
const pasteData = parser(e.clipboardData.getData('text/plain'))
```

with the contract that a user-provided `parsePaste` (or whatever we call it) return a 2d array of strings.

I'd be happy to open a PR if you would accept it.

**Comment by nadbm** [comment]
This sounds reasonable to me @bttmly , a PR with a test would be great
