### ISSUE TITLE
How to run examples in development?

### ISSUE THREAD

**Issue by bttmly** [nadbm/react-datasheet#40]
I'm trying to make some changes on a branch and test it with the examples in `docs/examples`. I tried running `npm run build` and also `npm run build:watch` then opening `docs/build/index.html` but I'm getting 404s for the JS and CSS bundles. Looking into this I also noticed that `docs/build` is not really in sync with `docs/public` -- for example the `<title>` element in `docs/build` says "React App" whereas the one in `docs/public` says "React Datasheet Component". Anyway, any pointers would be greatly appreciated!

**Comment by nadbm** [comment]
I'll look into this shortly

**Comment by nadbm** [comment]
I'll add this in the documentation but for quick reference: 
The examples folder is using a normal create-react-app;
```
cd react-datasheet/docs
npm install
npm start
```
Now it should open up your browser to host on localhost:3000
