### ISSUE TITLE
fixed header and column resize possible ?

### ISSUE THREAD

**Issue by kamaldlk** [nadbm/react-datasheet#45]
@nadbm @sediug  fixed header and column resize possible ?

**Comment by Sediug** [comment]
Impossible is nothing. But to do that... We need a lot of muscle it's not easy. http://schrodinger.github.io/fixed-data-table-2/example-resize.html It was implemented by facebook with divs. You are looking for an excel online and this is just a litle excel with some features not a complete spreadjs component xD. https://www.grapecity.com/en/spreadjs#solutions

**Comment by kamaldlk** [comment]
@Sediug thanks

**Comment by nadbm** [comment]
Unfortunately, not possible yet. Look at #30 and #26 that aims to do just that. 
Pull requests are welcome for these!
