### ISSUE TITLE
On edit, when you press Enter key, it should go to the cell below (like what Excel / Google Sheets does)

### ISSUE THREAD

**Issue by ericlau-solid** [nadbm/react-datasheet#47]
The down arrow key already does this, but in Excel during edit the Enter key has the same effect as the down arrow key, which I think end users expect but doesn't do right now in react-datasheet.

**Comment by Sediug** [comment]
It's easy to implement. I think it's a good idea. I offer myself to do it if the people like it.

**Comment by nadbm** [comment]
Seems like the right behaviour, feel free to make a pull request @Sediug  :)

**Comment by ericlau-solid** [comment]
I am trying the latest version at time of writing: 1.2.17, but the enter key doesn't behave like the down arrow key. This behavior is consistent in demo. Has npm been updated / published with latest changes?

**Comment by nadbm** [comment]
You’re right, depends on how editing is started (double click, enter). When typing directly it doesnt behave the same way. Im looking into this

**Comment by nadbm** [comment]
This should be properly fixed now on 1.2.18 @ericlau-solid

**Comment by Sediug** [comment]
Yeah, Thanks. I was on a rush with no time and I'm not proud of that implementation. Thanks @nadbm your implementation is cleaner and works as expected XD.
