### ISSUE TITLE
Cells lose custom className after editing it

### ISSUE THREAD

**Issue by sibutorovic** [nadbm/react-datasheet#48]
If you set a custom className for any cell with your own styles and edit the cell (change its value) on the datasheet that cell's classes are reset.

Example:
Bottom border on some cells with a custom class. 

![image](https://user-images.githubusercontent.com/4060696/33816364-1af4c1aa-de17-11e7-88bf-0833afbeb5c8.png)

And after editing any of those cells:

![image](https://user-images.githubusercontent.com/4060696/33816390-46ed4034-de17-11e7-8e81-b29c75521364.png)

Cell clases while selected:

![image](https://user-images.githubusercontent.com/4060696/33816400-576dc992-de17-11e7-8379-ff6cd38ff1ac.png)

Classes while editing:
![image](https://user-images.githubusercontent.com/4060696/33816403-658111a6-de17-11e7-99bd-b7e11fe36be7.png)

Classes after editing:

![image](https://user-images.githubusercontent.com/4060696/33816425-8f94940e-de17-11e7-95ef-3550e28bd1e7.png)

**Comment by nadbm** [comment]
How are you updating the cell? After the edit, does the cell data still have the className value?

**Comment by sibutorovic** [comment]
Im sorry, I got it to work thanks to your comment and it was quite simple.
