### ISSUE TITLE
Focus on cell component when editing

### ISSUE THREAD

**Issue by Dineshz** [nadbm/react-datasheet#51]
Is it possible to focus or pass the enter key event to the custom component when in editing mode (forceComponent is set to true) ?

My use case:
I have a custom Select options component inside the cell, with forceComponent: true. I would like to capture the enter key event/focus and open the Select dropdown.

**Comment by nadbm** [comment]
I'll have to make sure of this, but enter key event is currently being propagated.

https://nadbm.github.io/react-datasheet/ <-- check the last example with the select component

**Comment by Dineshz** [comment]
Since the autoFocus attribute is used on react-select, which focuses the component on mount, the Select component is focused. But when using forceComponent:true.. I cannot use autoFocus attribute, in which case, the focus event/enter key event does not propagate from ComponentCell.

Solution:
