### ISSUE TITLE
Add row in the middle of two rows

### ISSUE THREAD

**Issue by popo63301** [nadbm/react-datasheet#55]
How do you approach adding a row in the middle of two rows? I've read there's a system of key of each cell, so if you add a row in the middle of two, you probably need to change every key, no?

**Comment by nadbm** [comment]
The keys are set as default as a combo of row & column. But you may have your custom keys, and in that case, you just have to make sure they are unique. There is no problem for adding a new row, you just have to update your data to include the new dataset.
