### ISSUE TITLE
Very slow render when pasting or deleting several cells

### ISSUE THREAD

**Issue by stahlmanDesign** [nadbm/react-datasheet#56]
When I paste 20 rows with 10 columns (a modest amount of data) takes more than 10 seconds to render and it's all due to scripting.

If I introduce the method `shouldComponentUpdate` to render only every 500 ms, pasting data is twice as fast, but still very slow. It seems the cause is setting state for each a cell during the `onChange` method (the loop through the grid's rows and columns).

To get around this, I set up a separate `textarea` to paste the Excel data. I parse the pasted string to get `rows = string.split('\r\n')` and then `cells = rows[i].split('\t')`. I get the pasted `grid` and `this.setState({ grid })`. There is no delay (but it replaces the whole grid, not just a portion beginning at a selected cell).

Is there a way to paste into a cell but with improved speed? Possibly without setting state until the new grid has been processed?
![delay](https://user-images.githubusercontent.com/972804/34658049-b8084136-f3f9-11e7-89f0-c9e268e0c030.gif)

**Comment by nadbm** [comment]
Yep there is! 
When I released this, I did have to paste large amount of data so I left a handler for this purpose.
There is an api call: ```onPaste```
If you put a function there, you can set the whole state at once, and this will be much faster.

PS: We've met in person before I think. D3 tutorial if I recall correctly? Otherwise forgive my memory 😛

**Comment by stahlmanDesign** [comment]
OK, that works
```
  handleOnPaste = (rows)=>{
    let grid = []
    rows.forEach(cells =>{
      const row = cells.map(cell => {
        return { value: cell.data }
      })
      grid.push(row)
    })
    this.setState({ grid })
  }
```

Now, if `onPaste` had the cell info, e.g. `onPaste(array, cell)` then I could paste a smaller selection in the middle of the grid instead of replacing the whole grid — just like it works without `onPaste`, but faster.

It's still slow when deleting a bunch of selected cells. Would be good to have an `onDelete` (or `onCut` to copy tsv data to clipboard just like Excel) to set the grid with the selected cells cleared, quickly.

PS: yes, saw your D3 talk at Data Science Campaign, Complexe Desjardins, May 2016

**Comment by nadbm** [comment]
Probably should add a little more documentation on this. But the returned data format is the following: 
[[{cell,data}]]  (the cell has the extra info to compare your data source)


Is it slow on delete as well? I guess a pull request is welcome in that case

**Comment by nadbm** [comment]
Update:
#58  Fixes this with the onCellsChanged callback
