### ISSUE TITLE
pasting and deleting spam `onChange`

### ISSUE THREAD

**Issue by patrick-jones** [nadbm/react-datasheet#58]
This seems related to #56. When deleting a multi-cell selection, `onChange` gets called multiple times within a tight loop. This can cause a lot of unnecessary re-rendering when you update your state (or redux reducer, etc) from within a loop. I have even seen a hard to reproduce situation in which only the last cell in the range was deleted, I think because [`setState` doesn't always immediately update the state](https://reactjs.org/docs/react-component.html#setstate):

> setState() does not always immediately update the component. It may batch or defer the update until later. This makes reading this.state right after calling setState() a potential pitfall.

I think the solution is to support a version of `onChange` that takes an array of changed cells rather than just the one, as it does now.You have already taken a step towards this with `onPaste`, but that doesn't cover mass deletions. We can't change the arguments to `onChange` without breaking existing code, so I suggest

- Add a new handler that always takes an array of changes: `onChanges([{cell, i, j, newValue}, {cell, i, j, newValue}, {cell, i, j, newValue}, ...])` I'm not married to that name, but I can't think of anything better right now. If the user supplies `onChanges` we call that instead of `onChange`, just like `onPaste` works now.
- Deprecate and eventually remove `onChange` and `onPaste` so that there is a single handler no matter how many cells are affected.

If you like the idea I can PR it.

**Comment by nadbm** [comment]
Definitely like the idea. I prefer deprecating the idea of only having ```onChangeMultiple (easier to differentiate from onChanges)``` and get rid of ```onPaste```

**Comment by Sediug** [comment]
+1

**Comment by patrick-jones** [comment]
I will PR this, but I want to wait until #57 gets resolved. Easier merging.

**Comment by stahlmanDesign** [comment]
Thanks @patrick-jones I'm looking forward to your solution

**Comment by patrick-jones** [comment]
I'm almost done with this, but I've come across something that I'd like to get some feedback on.

Currently, `onChange` always includes the original cell as one of the arguments. `onPaste` does also, but with a catch: if you paste data that extends beyond the existing grid (e.g., you paste data four rows high on the last row) then the "out of bounds" pasted data are included, but `cell` is `null`. This is appropriate because this allows you to respond if you want -- you could automatically add rows to your model to hold the new data.

In making a single `onCellsChanged` handler, the array of changes can likewise have `null` cells for the same reason. This means that everyone's `onCellsChanged` handler has to guard against out of bounds values, even if you don't care about the extra data. It's not hard to avoid, but it's a potential landmine and a small annoyance.

So my idea is to have an optional second argument to `onCellsChanged` which would be all of the out of bounds data.  The objects in the first array would *always* have a non-null cell, and the row and column indices would be within the bounds of the current data grid. The objects in second array would *always* have null cells, and the row or col index (or both) would be outside of the current grid. If you don't care about the extra pasted data, just ignore the second argument.

Thoughts?

**Comment by nadbm** [comment]
So it would look like this: 
```onCellsChanged={(inBoundData, outOfBound) => {do something}}```
This looks clean to me. Are you keeping onPaste and onChange? We can slowly deprecate those as this function can handle both.

**Comment by patrick-jones** [comment]
That's the idea. And yes, `onChange` and `onPaste` will still be called unless `onCellsChanged` is available.
