### ISSUE TITLE
Selection of cells should be controlled

### ISSUE THREAD

**Issue by educastellano** [nadbm/react-datasheet#60]
I would like to show some properties outside the component regarding the selected cell. I managed to trigger an event by overriding the cell, but when I click outside the component the selection is gone.

How about something like this:
 
```
onSelected(selected) {
    this.setState({ selected })
}

<DataSheet 
    ...
    selected={this.state.selected}
    onSelected={onSelected}
    />
```

**Comment by nadbm** [comment]
@educastellano 
I realized I forgot to document this. Can you try the prop "onSelect" to see if it does the trick?

**Comment by educastellano** [comment]
The `onSelect` prop works, but when I set the cell to the state, the selection disappears from the component, probably for the same reason that disappears when you click outside. I can try to look at the code later to see why that happens... But I think this prop could work for me! 👍

**Comment by nadbm** [comment]
@educastellano can you make a fiddle with the issue? The selection should not disappear on a state change.

**Comment by educastellano** [comment]
I managed to make a fiddle: https://jsfiddle.net/69z2wepo/99781/ I had some problems importing the library so I ended up including all the files in the JS section - seems to not be any collision with variable names. The example code is at the end.

The problem is happening when I pass a custom cell in the `cellRenderer` prop. If I remove this prop it works correctly.

**Comment by patrick-jones** [comment]
Have a look at the changes I made here: [https://jsfiddle.net/j7y0ga47/](https://jsfiddle.net/j7y0ga47/). You want to avoid using arrow functions as properties (more background [here](https://medium.freecodecamp.org/why-arrow-functions-and-bind-in-reacts-render-are-problematic-f1c08b060e36)).

**Comment by nadbm** [comment]
As @patrick-jones mentioned, you want to avoid the arrow functions. His fiddle seems to be the same as above. Here is one without the arrow function: https://jsfiddle.net/j7y0ga47/1/

**Comment by educastellano** [comment]
@patrick-jones @nadbm Perfect!! Thanks! 😃 

The other problem I had is that I lose the selection when click outside the component, which I have fixed here: #63 Let me know what you think.

**Comment by patrick-jones** [comment]
Bah! I must have forgotten to save the changes to the fiddle.

**Comment by educastellano** [comment]
@patrick-jones no problem! 😃 

Another thing, I'll probably need the selection of all the cells in case of selecting more than one. What about:

```js
onSelected(selected, start, end) {}
```

`selected` would still be a single cell or the last cell selected.

**Comment by nadbm** [comment]
@educastellano that sounds good. Currently, the onSelect method wasn't documented. So feel free to make a pull request against that.

**Comment by patrick-jones** [comment]
I also like the idea of being able to set the selection as a property. It's handy that the component manages selection for you, but sometimes it would be nice to control that externally (for example, to restore the last selection from a previous editing session).

**Comment by educastellano** [comment]
@patrick-jones @nadbm 
Maybe it should be optional. If the `selected` prop is set the selection is controlled, otherwise we keep `start` and `end` in the state. 
I could work on that when I have some time, not a priority for me at the moment.

**Comment by patrick-jones** [comment]
@educastellano agree about it being optional

**Comment by educastellano** [comment]
🎉 I've made an implementation of this here: #74

**Comment by nadbm** [comment]
Closing this issue after @educastellano's PR
