### ISSUE TITLE
need Help

### ISSUE THREAD

**Issue by kamaldlk** [nadbm/react-datasheet#64]
{
  "Id": "GridData",
  "Columns": [
    {
      "Key": "Id",
      "Name": "Id",
      "Width": 40,
      "Fixed": true
    },
    {
      "Key": "task",
      "Name": "Title",
      "Width": 100,
      "Fixed": true
    },
    {
      "Key": "priority",
      "Name": "Priority",
      "Width": 125
    },
    {
      "Key": "issueType",
      "Name": "Issue Type",
      "Width": 150
    },
    {
      "Key": "taskInfo",
      "Name": "Task info",
      "Width": 400
    },
    {
      "Key": "complete",
      "Name": "% Complete",
      "Width": 200
    },
    {
      "Key": "startDate",
      "Name": "Start Date",
      "Width": 300
    },
    {
      "Key": "completeDate",
      "Name": "Expected Complete",
      "Width": 300
    },
    {
      "Key": "notes",
      "Name": "Task notes",
      "Width": 300,
      "RightFixed":false
    }
  ],
  "Table::Employee": [
    {
      "Id": 1,
      "priority": "OrangeRed",
      "issueType": "Major",
      "task": "Task 1",
      "complete": 100,
      "taskInfo": "Test",
      "startDate": "Sun May 08 2016 13:59:24 GMT+0530 (IST)",
      "completeDate": "Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
      "notes": ""
    },
    {
      "Id": 2,
      "priority": "OrangeRed",
      "issueType": "Major",
      "task": "Task 1",
      "complete": 100,
      "taskInfo": "Test",
      "startDate": "Sun May 08 2016 13:59:24 GMT+0530 (IST)",
      "completeDate": "Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
      "notes": ""
    },
    {
      "Id": 3,
      "priority": "OrangeRed",
      "issueType": "Major",
      "task": "Task 1",
      "complete": 100,
      "taskInfo": "Test",
      "startDate": "Sun May 08 2016 13:59:24 GMT+0530 (IST)",
      "completeDate": "Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
      "notes": ""
    },
    {
      "Id": 4,
      "priority": "OrangeRed",
      "issueType": "Major",
      "task": "Task 1",
      "complete": 100,
      "taskInfo": "Test",
      "startDate": "Sun May 08 2016 13:59:24 GMT+0530 (IST)",
      "completeDate": "Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
      "notes": ""
    },
    {
      "Id": 5,
      "priority": "OrangeRed",
      "issueType": "Major",
      "task": "Task 1",
      "complete": 100,
      "taskInfo": "Test",
      "startDate": "Sun May 08 2016 13:59:24 GMT+0530 (IST)",
      "completeDate": "Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
      "notes": ""
    }
    ,
    {
      "Id": 6,
      "priority": "OrangeRed",
      "issueType": "Major",
      "task": "Task 1",
      "complete": 100,
      "taskInfo": "Test",
      "startDate": "Sun May 08 2016 13:59:24 GMT+0530 (IST)",
      "completeDate": "Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
      "notes": ""
    },
    {
      "Id": 7,
      "priority": "OrangeRed",
      "issueType": "Major",
      "task": "Task 1",
      "complete": 100,
      "taskInfo": "Test",
      "startDate": "Sun May 08 2016 13:59:24 GMT+0530 (IST)",
      "completeDate": "Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
      "notes": ""
    }
  ]
}

This Kind of data structure how can i use react data sheet

**Comment by Sediug** [comment]
Next time use prettyfier please, like [jsonformatter](https://jsonformatter.curiousconcept.com/). ;) I'll take a look.
```json
{  
   "Id":"GridData",
   "Columns":[  
      {  
         "Key":"Id",
         "Name":"Id",
         "Width":40,
         "Fixed":true
      },
      {  
         "Key":"task",
         "Name":"Title",
         "Width":100,
         "Fixed":true
      },
      {  
         "Key":"priority",
         "Name":"Priority",
         "Width":125
      },
      {  
         "Key":"issueType",
         "Name":"Issue Type",
         "Width":150
      },
      {  
         "Key":"taskInfo",
         "Name":"Task info",
         "Width":400
      },
      {  
         "Key":"complete",
         "Name":"% Complete",
         "Width":200
      },
      {  
         "Key":"startDate",
         "Name":"Start Date",
         "Width":300
      },
      {  
         "Key":"completeDate",
         "Name":"Expected Complete",
         "Width":300
      },
      {  
         "Key":"notes",
         "Name":"Task notes",
         "Width":300,
         "RightFixed":false
      }
   ],
   "Table::Employee":[  
      {  
         "Id":1,
         "priority":"OrangeRed",
         "issueType":"Major",
         "task":"Task 1",
         "complete":100,
         "taskInfo":"Test",
         "startDate":"Sun May 08 2016 13:59:24 GMT+0530 (IST)",
         "completeDate":"Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
         "notes":""
      },
      {  
         "Id":2,
         "priority":"OrangeRed",
         "issueType":"Major",
         "task":"Task 1",
         "complete":100,
         "taskInfo":"Test",
         "startDate":"Sun May 08 2016 13:59:24 GMT+0530 (IST)",
         "completeDate":"Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
         "notes":""
      },
      {  
         "Id":3,
         "priority":"OrangeRed",
         "issueType":"Major",
         "task":"Task 1",
         "complete":100,
         "taskInfo":"Test",
         "startDate":"Sun May 08 2016 13:59:24 GMT+0530 (IST)",
         "completeDate":"Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
         "notes":""
      },
      {  
         "Id":4,
         "priority":"OrangeRed",
         "issueType":"Major",
         "task":"Task 1",
         "complete":100,
         "taskInfo":"Test",
         "startDate":"Sun May 08 2016 13:59:24 GMT+0530 (IST)",
         "completeDate":"Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
         "notes":""
      },
      {  
         "Id":5,
         "priority":"OrangeRed",
         "issueType":"Major",
         "task":"Task 1",
         "complete":100,
         "taskInfo":"Test",
         "startDate":"Sun May 08 2016 13:59:24 GMT+0530 (IST)",
         "completeDate":"Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
         "notes":""
      },
      {  
         "Id":6,
         "priority":"OrangeRed",
         "issueType":"Major",
         "task":"Task 1",
         "complete":100,
         "taskInfo":"Test",
         "startDate":"Sun May 08 2016 13:59:24 GMT+0530 (IST)",
         "completeDate":"Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
         "notes":""
      },
      {  
         "Id":7,
         "priority":"OrangeRed",
         "issueType":"Major",
         "task":"Task 1",
         "complete":100,
         "taskInfo":"Test",
         "startDate":"Sun May 08 2016 13:59:24 GMT+0530 (IST)",
         "completeDate":"Fri Jun 24 2016 17:54:05 GMT+0530 (IST)",
         "notes":""
      }
   ]
}
```

**Comment by nadbm** [comment]
@kamaldlk 
The documentation is fairly extensive, these type of questions don't really belong in issues. ≈

**Comment by Sediug** [comment]
Agree with @nadbm but it's easy, it's just change the data dimensions to have a matrix.

```jsx
const tableName = 'Table::Employee';
const grid = [
	data.Columns.map(column => {
        // build header row
		return {
            value: column.Name,
            width: column.Width,
            fixed: column.Fixed || false
        };	
    }),
	...data[tableName].map(row => {
        // Build each content row
        return data.Columns.map(column => {
            return {
                value: row[column.Key],
                width: column.Width
            };
        });

    })
];

<ReactFixedDataSheet
	data={ grid }
	valueRenderer={ cell => cell.value }
	onChange={(cell) => {...}}
/>
```

**Comment by kamaldlk** [comment]
Thanks
