### ISSUE TITLE
Clearing the cell value for a component cell

### ISSUE THREAD

**Issue by charleschenster** [nadbm/react-datasheet#69]
Hi @nadbm, I'm looking for an example where you use a react-select component and you're able to clear the cell value with the `delete` or `backspace` key. Is this possible? I tried adapting the example on https://nadbm.github.io/react-datasheet/ and I was unable to do get that to work.

**Comment by nadbm** [comment]
Slightly more complex but doable. Look at the custom renderer example here : 
https://github.com/nadbm/react-datasheet/blob/master/docs/src/examples/CustomRendererSheet.js#L57

**Comment by charleschenster** [comment]
@nadbm Thanks for the quick response! That was exactly what I needed. 🙏thanks!
