### ISSUE TITLE
text overflow?

### ISSUE THREAD

**Issue by rileytg** [nadbm/react-datasheet#7]
Not gonna call the current behavior a "bug" but i figure a thread on what should be done for overflow is a worthwhile discussion. 

Current Behavior: 
<img width="576" alt="react_datasheet_component" src="https://cloud.githubusercontent.com/assets/692817/24668420/ac689b96-191b-11e7-8cf5-71ef6a40f2cf.png">

Google sheets:
<img width="695" alt="untitled_spreadsheet_-_google_sheets_and_terminal_ _-bash_ _182x58" src="https://cloud.githubusercontent.com/assets/692817/24668433/b1a5818c-191b-11e7-8803-4024dc1d7456.png">

Does it makes sense to truncate (overflow hidden) when the next cell is filled, but not when empty? What if it is going to overlap a a third cell that is filled... do we allow overflow into the second empty cell then hide when reaching the third?

**Comment by nadbm** [comment]
Overflow hidden makes sense. The only issue I can see if that if the cell contains a component that is meant to overflow (for example a dropdown), it will get hidden too.
Maybe having overflow hidden on the x axis would work?

**Comment by hugozap** [comment]
and extension point could be added in the form of a property e.g , cellStyle or a method getCellStyle(data) that gets evaluated against each cell data to obtain the value container style for that cell.
