### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by astegmaier** [nadbm/react-datasheet#70]
First thing, I wanted to say thank you for building and contributing such a high quality component. I'm playing around with it now, and it's quite impressive.

I was was looking to integrate this into a react project that used typescript, and I was hoping to get all the typescript goodness that I'm used to. I didn't see any definition files in this project or any existing definitions on @types, and I was wondering if anyone has hit this need before and if there are any solutions that already exist?

If not, would you be open to a PR to add types? I could also try to contribute to @types, but it seems like it might be a better experience for everyone if they were integrated into the core library.

**Comment by nadbm** [comment]
Thanks for the kind words. I would be open to a PR, I do not use typescript on my workflow, so haven't gotten around to adding them.

**Comment by astegmaier** [comment]
Awesome! I got started working on it in [a fork](https://github.com/astegmaier/react-datasheet), and I think I got [a basic scenario](https://github.com/astegmaier/react-datasheet/commit/3cc77068f9f83ecb44b8c2f8f9ac51b3bca59756) off the ground by following the example already set by @weswigham at [his repo](https://github.com/weswigham/AtTypes-react-datasheet). I'll let you know when it's ready to review (it might be a while because I'm doing this in my spare time).

**Comment by weswigham** [comment]
If the package maintainer isn't willing to actively use and update the definition files themselves, you should contribute type definitions to DefinitelyTyped instead, that way they can stay in the community and avoid burdening the package author. I just never got around to it because I just made the types for a one off project I made. :D

**Comment by weswigham** [comment]
Oh, it's also worth noting that the work around I had in my readme hopefully isn't need anymore, since I've been working on updating TS itself to do proper inference for generic JSX components :3

**Comment by astegmaier** [comment]
What do you think @nadbm ? I'm happy to contribute to @types instead. It's definitely more convenient for consumers who use typescript to have them come for free as part of the main package and benefit from attention from the core maintainers, but I don't want to burden you if you're already fully booked.

**Comment by nadbm** [comment]
If it's on the package, I will try to maintain it. I'm not actively developing it so it will not be too bad to keep it up-to-date

**Comment by astegmaier** [comment]
I created #72 to add typescript definitions. I've tested it out in the context of a personal typescript project that exercises all the functionality of the package, and it seems to work. I also added a section to the readme to help get other folks started. Let me know if you have any feedback!

**Comment by wfortin** [comment]
Any reason why this isn't published in npm? I'd love to be able to use the TS definitions.

**Comment by nadbm** [comment]
Seems like I never published 1.3.4, my bad @wfortin. It's up now

**Comment by wfortin** [comment]
Great thanks!

**Comment by shawnmitchell** [comment]
N00b question here. I see `"main": "lib/index.js",
  "types": "types/react-datasheet.d.ts"` in the project's package.json but it seems yarn didn't install it. Any help would be appreciated!

**Comment by astegmaier** [comment]
@shawnmitchell and @nadbm - I think this might be a bug. I think we need to add the `types` folder to the `files` node in `package.json`. Sorry for not catching this - my testing was focused on consuming it based off of my local repo, but I didn't try actually creating the npm package.

A quick workaround while you wait for the fix would be: clone the nadbm/react-datasheet locally, and run `yarn link` in it.

**Comment by nadbm** [comment]
@shawnmitchell added the types folder in the file node. Let me know if this works for you @shawnmitchell
