### ISSUE TITLE
`onChange` shouldn't be called for cells using `component` option

### ISSUE THREAD

**Issue by zachguo** [nadbm/react-datasheet#73]
bug found after upgraded to v1.3.2 from v1.2.11.

I'm using a `<select ... />` inside a cell, however, datasheet's `onChange` is called when cell loses focus, so that empty value overrides my `select` input.

**Comment by nadbm** [comment]
I'll check it out @zachguo , can you provide the simplest example to reproduce? thanks

**Comment by zachguo** [comment]
@nadbm I'm not able to now. Maybe I'll try to add a test case later.

**Comment by zachguo** [comment]
I worked around this issue by using newly provided `dataEditor` option ( and `props.onCommit`) instead of old `component` option.

@nadbm  It seems that `component` and `forceComponent` options can be removed, since there are `dataEditor` and `valueViewer` replacing their functionalities now.

**Comment by nadbm** [comment]
great @zachguo thanks for confirming. 
yes I will deprecate them soon. The dataEditor and valueViewer are the way to go 😄
