### ISSUE TITLE
issue in display columns and rows

### ISSUE THREAD

**Issue by kamaldlk** [nadbm/react-datasheet#78]
I Have created a table with 15 columns and 14 rows table, not displaying properly 

Here example. : https://codesandbox.io/s/l2xo65l9pq 
![screen shot 2018-03-28 at 7 28 42 am](https://user-images.githubusercontent.com/9652523/38004399-b1ff2b08-3259-11e8-8e2f-d8a32bdbb453.png)

**Comment by nadbm** [comment]
You seemed to have copied an example code that is meant to show how to render with tables/divs. If you choose to render with table, it will display correctly.

I try not to be rude @kamaldlk but again, please read the docs before opening issues. This is the third time from you.
