### ISSUE TITLE
Cell blinks as updated when no value is changed

### ISSUE THREAD

**Issue by bartektartanus** [nadbm/react-datasheet#79]
When `valueRenderer` returns an object or an array (which are still rendered correctly) instead of just single value then this cell 'blinks' as updated even if no value is changed. This is caused by this line:
https://github.com/nadbm/react-datasheet/blob/2b0c0773a02f8b0ccefc480a93922f5465b448dd/src/DataCell.js#L42

I've changed it to:
```
if (!initialValue(nextProps).equals(initialValue(this.props))) { 
```
 and looks like it helped for object/arrays (but it fails for singe values as there is no equals method :)).

**Comment by nadbm** [comment]
Rendering an object doesn't make too much sense but I'm guessing it is automatically being converted to a string when it is displayed. 
So if you just convert the arrays or objects into strings on your valueRenderer function, they should work without the change.

**Comment by bartektartanus** [comment]
Not exactly. I'm trying to return value with button next to it, like this:

```
<ReactDataSheet
  data={this.state.grid}
  valueRenderer={(cell, i, j) => {
    return [cell.value, <button className="btn btn-danger" onClick={() => this.method()}>Button</button>];
  }}
...
```

and this is rendered just fine. Calling `toString()` will return "value[object Object]" instead of a button, which is not what I want. Maybe there is a better approach to it?

**Comment by nadbm** [comment]
So valueRenderer is very much meant for data only. If you want to have components in each cell you have two options currently : 

Use the 'component' per cell:

https://github.com/nadbm/react-datasheet#cells-with-underlying-component

or use the 'cellRenderer' option (preferable):

https://github.com/nadbm/react-datasheet#advanced-options
https://github.com/nadbm/react-datasheet#cell-renderer
