### ISSUE TITLE
Copy-Paste from excel error

### ISSUE THREAD

**Issue by mdanielcristian** [nadbm/react-datasheet#83]
Whenever I copy-paste from excel more that one row, whether we are talking about changes or additions, I receive one extra change/addition with value "" in the onCellsChanged handler (on a row that doesn't have changes/additions).
Should be easy to reproduce.
In the example below I have 3 rows with OOB rendering, simple text as follows:
  - 1 2 3 on first row
  - 4 5 6 on second row
  - 7 8 9 on last row

I then paste from excel two rows as follows:
  - a b on first row
 - c d on second row

Unexpected behavior: first cell on last row, that previously had 7 in it, is cleared.
![paste_not_working_grid](https://user-images.githubusercontent.com/30260770/38558823-0e347fb0-3cda-11e8-98ed-400c5e6663df.gif)

**Comment by nadbm** [comment]
Seems like excel is pasting data oddly. You might wanna use the `parsePaste` to remove any odd delimiters:
https://github.com/nadbm/react-datasheet#options

**Comment by mdanielcristian** [comment]
Ok, will do, thanks. 
Since it was the default parsePaste method being used, I thought you might want to include a fix in the next release.
