### ISSUE TITLE
For copy paste extra cell shown as selected

### ISSUE THREAD

**Issue by monikaxx** [nadbm/react-datasheet#85]
When we do copy paste, extra cell is getting selected.
Steps to reproduce : 
1. open any sample excel file
2. copy value from it
3. paste in datasheet
4. extra cell getting selected

**Comment by monikaxx** [comment]
ReactDataSheet onCellsChanged needs blank value check condition

**Comment by nadbm** [comment]
this seems like a excel specific issue, I'll have a look soon but for now you can use parsepaste props as mentionned here #83

**Comment by nadbm** [comment]
@monikaxx  the parsePaste function takes your raw pasted string. You should remove any extra space, commas or tabs that comes from pasting from excel.
