### ISSUE TITLE
need Help on cell selection Ui 

### ISSUE THREAD

**Issue by kamaldlk** [nadbm/react-datasheet#91]
@nadbm while selecting cell range UI looks something need to improve, is there any option to do 
![screen shot 2018-05-02 at 10 52 29 am](https://user-images.githubusercontent.com/9652523/39506541-d3fa10c0-4df6-11e8-8a78-faac17092ee8.png) 
![screen shot 2018-05-02 at 10 51 43 am](https://user-images.githubusercontent.com/9652523/39506542-d8972fdc-4df6-11e8-8ea6-1d8d9b19f31f.png)

**Comment by nadbm** [comment]
Are you talking about the white spacing? 
The cellspacing can be added via the css. Otherwise there isnt any option to make it look like that
