### ISSUE TITLE
Is there a way to get the values of an excel drop-down list when that cell is pasted to a react-datasheet?

### ISSUE THREAD

**Issue by shawnmitchell** [nadbm/react-datasheet#93]
If I paste a drop-down list from an excel spreadsheet to a ReactDataSheet component I get the current value but not the list of possible values. Is there a way to retrieve the whole list of options?

**Comment by nadbm** [comment]
Hey @shawnmitchell, not sure I understand correctly, if you copy from excel, if it doesn't get transferred to the clipboard, there is no way for a component to retrieve it.

**Comment by shawnmitchell** [comment]
Fair point :-/
