### ISSUE TITLE
Mocha giving timeout error on testing

### ISSUE THREAD

**Issue by greatwillow** [nadbm/react-datasheet#94]
On running the test script, a timeout error is being generated, resulting in failed tests.  Here is a screenshot of the error:

![timeouterror](https://user-images.githubusercontent.com/15651001/40880485-e9e370a6-667f-11e8-93e7-141d92eaf43b.png)

**Comment by nadbm** [comment]
@greatwillow is this after any changes? I checked out the master branch just now and it seems to be running fine

**Comment by greatwillow** [comment]
Ok @nadbm !  I was checking this on a fresh pull from master so the codebase should have been inline with yours, however, perhaps your system is running faster than mine, and so would not cause this error for you?  There is a simple fix for this that I am creating a pull request on, though can be cancelled if you see it as unnecessary.
